[package]
name = "dominate-2020"
version = "0.1.0"
authors = ["Mark Gulbrandsen <mark.gulbrandsen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = {verion = "0.15.0", features = ["metal"]}
